'use client'

import { ArrowRight, Bell, Check, Crown, Eye, Percent, TrendingUp, Zap } from 'lucide-react'
import { motion } from 'framer-motion'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { cn } from '@/lib/utils'

type PromoSectionsProps = { onLoginRequired: (message: string) => void }

export function PromoSections({ onLoginRequired }: PromoSectionsProps) {
  const plans = [{ name: 'Basic', price: 'EUR49', features: ['Profilseite', 'Kontaktdaten', '5 Fotos'], popular: false }, { name: 'Premium', price: 'EUR149', features: ['Top Platzierung', 'Unbegrenzte Fotos', 'Verifiziert Badge', 'Reservierungssystem'], popular: true }, { name: 'Sponsored', price: 'EUR299', features: ['Homepage Featured', 'Top Anzeige Badge', 'Statistiken', 'Priority Support'], popular: false }]
  const benefits = [{ icon: <Zap className="h-6 w-6" />, text: 'Reservierungsprioritaet' }, { icon: <Bell className="h-6 w-6" />, text: 'Auto-Booking' }, { icon: <Percent className="h-6 w-6" />, text: '25% Rabatt' }, { icon: <Eye className="h-6 w-6" />, text: 'Exklusiver Inhalt' }]

  return (
    <>
      <section id="premium" className="bg-linear-to-b from-[#0a0a0f] to-[#150a15] py-20"><div className="mx-auto max-w-7xl px-6"><motion.div initial={false} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="relative overflow-hidden rounded-3xl"><div className="absolute inset-0 bg-linear-to-r from-[#8b1a4a] to-[#6b3fa0]" /><div className="relative z-10 px-8 py-16 text-center md:px-16 md:py-20"><div className="mb-6 inline-flex h-20 w-20 items-center justify-center rounded-full bg-white/20"><Crown className="h-10 w-10 text-white" /></div><h2 className="mb-4 text-3xl font-bold text-white sm:text-4xl md:text-5xl">Premium Mitgliedschaft</h2><p className="mx-auto mb-8 max-w-2xl text-lg text-white/80">Prioritaets-Reservierung, automatische Buchung bei Verfuegbarkeit und exklusive Rabatte.</p><div className="mx-auto mb-8 grid max-w-3xl grid-cols-2 gap-4 md:grid-cols-4">{benefits.map((benefit) => <div key={benefit.text} className="rounded-xl bg-white/10 p-4 backdrop-blur-sm"><div className="mb-2 flex justify-center text-white">{benefit.icon}</div><div className="text-sm text-white">{benefit.text}</div></div>)}</div><Button size="lg" onClick={() => onLoginRequired('Sie muessen sich anmelden, um Premium-Funktionen nutzen zu koennen.')} className="rounded-full bg-white px-8 text-[#8b1a4a] hover:bg-white/90">Jetzt Premium werden <ArrowRight className="ml-2 h-4 w-4" /></Button></div></motion.div></div></section>
      <section id="werbung" className="bg-[#0a0a0f] py-20"><div className="mx-auto max-w-7xl px-6"><div className="mb-12 text-center"><Badge className="mb-4 border-[#8b1a4a]/30 bg-[#8b1a4a]/20 text-[#b76e79]"><TrendingUp className="mr-1 h-3 w-3" /> Fuer Betriebe</Badge><h2 className="mb-4 text-3xl font-bold text-white">Werben auf DesireMap.de</h2><p className="text-gray-400">Tausende potenzielle Kunden taeglich erreichen</p></div><div className="grid grid-cols-1 gap-6 md:grid-cols-3">{plans.map((plan) => <div key={plan.name} className={cn('relative p-6 rounded-2xl bg-white/5 backdrop-blur-sm border', plan.popular ? 'border-[#8b1a4a]/50 ring-2 ring-[#8b1a4a]/20' : 'border-white/5')}>{plan.popular && <div className="absolute -top-3 left-1/2 -translate-x-1/2"><Badge className="border-0 bg-linear-to-r from-[#8b1a4a] to-[#6b3fa0] text-white">Beliebt</Badge></div>}<h3 className="mb-2 text-xl font-semibold text-white">{plan.name}</h3><div className="mb-4 text-3xl font-bold text-white">{plan.price}<span className="text-base font-normal text-gray-400">/Monat</span></div><ul className="mb-6 space-y-3">{plan.features.map((feature) => <li key={feature} className="flex items-center gap-2 text-sm text-gray-300"><Check className="h-4 w-4 text-green-400" /> {feature}</li>)}</ul><Button onClick={() => onLoginRequired('Sie muessen sich anmelden, um ein Werbepaket buchen zu koennen.')} className={cn('w-full', plan.popular ? 'bg-linear-to-r from-[#8b1a4a] to-[#6b3fa0] text-white border-0' : 'bg-white/5 hover:bg-white/10 text-white border border-white/10')}>Auswaehlen</Button></div>)}</div></div></section>
    </>
  )
}
